### ISSUE TITLE
导入照片后返回到预览页面时会抛出autoFocus failed异常

### ISSUE THREAD

**Issue by Nevall** [bingoogolapple/BGAQRCode-Android#144]
06-06 16:44:31.503 20655-20655/cn.bingoogolapple.qrcode.zxingdemo E/CameraPreview: java.lang.RuntimeException: autoFocus failed
                                                                                   java.lang.RuntimeException: autoFocus failed
                                                                                       at android.hardware.Camera.native_autoFocus(Native Method)
                                                                                       at android.hardware.Camera.autoFocus(Camera.java:1258)
                                                                                       at cn.bingoogolapple.qrcode.core.CameraPreview.showCameraPreview(CameraPreview.java:73)
                                                                                       at cn.bingoogolapple.qrcode.core.CameraPreview.setCamera(CameraPreview.java:34)
                                                                                       at cn.bingoogolapple.qrcode.core.QRCodeView.startCameraById(QRCodeView.java:103)
                                                                                       at cn.bingoogolapple.qrcode.core.QRCodeView.startCamera(QRCodeView.java:94)
                                                                                       at cn.bingoogolapple.qrcode.core.QRCodeView.startCamera(QRCodeView.java:78)
                                                                                       at cn.bingoogolapple.qrcode.zxingdemo.TestScanActivity.onStart(TestScanActivity.java:38)
                                                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                                       at android.app.Activity.performStart(Activity.java:6699)
                                                                                       at android.app.Activity.performRestart(Activity.java:6773)
                                                                                       at android.app.Activity.performResume(Activity.java:6778)
                                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3407)
                                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3470)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Nevall** [comment]
barcodescanner 库也有这个异常，参考
https://github.com/dm77/barcodescanner/issues/7

**Comment by allenyulun** [comment]
请问你解决了吗
