### ISSUE TITLE
报了一个RuntimeException，An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by cr1992** [bingoogolapple/BGAQRCode-Android#204]
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.RuntimeException: getParameters failed (empty parameters)
	at android.hardware.Camera.native_getParameters(Native Method)
	at android.hardware.Camera.getParameters(Camera.java:2085)
	at cn.bingoogolapple.qrcode.core.c.a(ProcessDataTask.java:43)
	at cn.bingoogolapple.qrcode.core.c.doInBackground(ProcessDataTask.java:7)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
这是我使用的问题还是控件的问题？

**Comment by yxlku** [comment]
楼主解决了吗

**Comment by kekegdsz** [comment]
1.2.2
