### ISSUE TITLE
扫描崩溃了

### ISSUE THREAD

**Issue by hudan2714** [bingoogolapple/BGAQRCode-Android#225]
java.lang.RuntimeException: An error occured while executing doInBackground()
                                                   at android.os.AsyncTask$3.done(AsyncTask.java:299)
                                                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:239)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                   at java.lang.Thread.run(Thread.java:841)
                                                Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
                                                   at com.google.zxing.pdf417.decoder.DecodedBitStreamParser.decode(DecodedBitStreamParser.java:96)
                                                   at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decodeCodewords(PDF417ScanningDecoder.java:534)
                                                   at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResultFromAmbiguousValues(PDF417ScanningDecoder.java:309)
                                                   at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResult(PDF417ScanningDecoder.java:278)
                                                   at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decode(PDF417ScanningDecoder.java:124)
                                                   at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:87)
                                                   at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:61)
                                                   at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
                                                   at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
                                                   at cn.bingoogolapple.qrcode.zxing.ZXingView.processData(ZXingView.java:45)
                                                   at cn.bingoogolapple.qrcode.core.ProcessDataTask.doInBackground(ProcessDataTask.java:66)
                                                   at cn.bingoogolapple.qrcode.core.ProcessDataTask.doInBackground(ProcessDataTask.java:7)
                                                   at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080) 
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573) 
                                                   at java.lang.Thread.run(Thread.java:841)

**Comment by yvonneyl** [comment]
我的问题跟你一样也是在5.0上崩溃
