### ISSUE TITLE
在Fragment中点击返回键会奔溃

### ISSUE THREAD

**Issue by qianshengta** [bingoogolapple/BGAQRCode-Android#255]
在Fragment中点击返回键会奔溃

04-16 15:59:00.847 26458-26499/? E/Market-URLConnectionInterceptor: failed to enable url interceptor
                                                                    java.lang.Error: Factory already set
                                                                        at java.net.URL.setURLStreamHandlerFactory(URL.java:112)
                                                                        at com.xiaomi.market.data.a.l.a(SourceFile:80)
                                                                        at com.xiaomi.market.data.bq.run(SourceFile:54)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)

**Comment by qianshengta** [comment]
问题解决了，

**Comment by HoikanChan** [comment]
请问怎么解决的？
