### ISSUE TITLE
你好，我用的pda机器，7.0的原生系统，只有一个后置摄像头，出现很多次打开摄像头失败的情况

### ISSUE THREAD

**Issue by bbbBBBSG** [bingoogolapple/BGAQRCode-Android#378]
你好，我用的pda机器，7.0的原生系统，只有一个后置摄像头，出现很多次打开摄像头失败的情况
    implementation 'cn.bingoogolapple:bga-qrcode-zbar:1.3.6'

**Comment by bingoogolapple** [comment]
错误日志贴一下

**Comment by bbbBBBSG** [comment]
```
2018-12-17 09:13:30.562 23388-23388/com.demo W/CameraBase: An error occurred while connecting to camera 0: Service not available
2018-12-17 09:13:30.562 23388-23388/com.demo W/System.err: java.lang.RuntimeException: Fail to connect to camera service
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.hardware.Camera.<init>(Camera.java:643)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.hardware.Camera.open(Camera.java:491)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startCameraById(QRCodeView.java:174)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startCamera(QRCodeView.java:142)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startCamera(QRCodeView.java:130)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at com.demo.ui.activity.ScanCodeActivity.onStart(ScanCodeActivity.java:49)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.app.Activity.performStart(Activity.java:6683)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.os.Looper.loop(Looper.java:203)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6251)
2018-12-17 09:13:30.565 23388-23388/com.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-12-17 09:13:30.566 23388-23388/com.demo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
2018-12-17 09:13:30.566 23388-23388/com.demo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
2018-12-17 09:13:30.586 23388-23388/com.demo W/CameraBase: An error occurred while connecting to camera 0: Service not available
2018-12-17 09:13:30.587 23388-23388/com.demo W/System.err: java.lang.RuntimeException: Fail to connect to camera service
2018-12-17 09:13:30.587 23388-23388/com.demo W/System.err:     at android.hardware.Camera.<init>(Camera.java:643)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at android.hardware.Camera.open(Camera.java:491)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startCameraById(QRCodeView.java:174)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startCamera(QRCodeView.java:142)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startCamera(QRCodeView.java:130)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startSpot(QRCodeView.java:206)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.startSpotAndShowRect(QRCodeView.java:242)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at com.demo.ui.activity.ScanCodeActivity.onStart(ScanCodeActivity.java:52)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at android.app.Activity.performStart(Activity.java:6683)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
2018-12-17 09:13:30.588 23388-23388/com.demo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
2018-12-17 09:13:30.589 23388-23388/com.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
2018-12-17 09:13:30.589 23388-23388/com.demo W/System.err:     at android.os.Looper.loop(Looper.java:203)
2018-12-17 09:13:30.589 23388-23388/com.demo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6251)
2018-12-17 09:13:30.589 23388-23388/com.demo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-12-17 09:13:30.589 23388-23388/com.demo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
2018-12-17 09:13:30.589 23388-23388/com.demo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

应该是手机的问题，我试了很多其他的应用都打不开，这个是pda手持设备，只有后面一个相机
