### ISSUE TITLE
华为平板 M5青春版 扫描二维码  Log打印这个warning  怎么修改 

### ISSUE THREAD

**Issue by ggyg123** [bingoogolapple/BGAQRCode-Android#382]
2018-12-27 10:50:03.413	 W/System.err: java.lang.RuntimeException: autoFocus failed
2018-12-27 10:50:03.413  W/System.err:     at android.hardware.Camera.native_autoFocus(Native Method)
2018-12-27 10:50:03.413  W/System.err:     at android.hardware.Camera.autoFocus(Camera.java:1331)
2018-12-27 10:50:03.413  W/System.err:     at cn.bingoogolapple.qrcode.core.CameraPreview.handleFocusMetering(CameraPreview.java:248)
2018-12-27 10:50:03.413  W/System.err:     at cn.bingoogolapple.qrcode.core.CameraPreview.onScanBoxRectChanged(CameraPreview.java:148)
2018-12-27 10:50:03.413  W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.onScanBoxRectChanged(QRCodeView.java:423)
2018-12-27 10:50:03.413  W/System.err:     at cn.bingoogolapple.qrcode.core.ScanBoxView.calFramingRect(ScanBoxView.java:547)
2018-12-27 10:50:03.413  W/System.err:     at cn.bingoogolapple.qrcode.core.ScanBoxView.onSizeChanged(ScanBoxView.java:533)
2018-12-27 10:50:03.414  W/System.err:     at android.view.View.sizeChange(View.java:19914)
2018-12-27 10:50:03.414  W/System.err:     at android.view.View.setFrame(View.java:19875)
2018-12-27 10:50:03.414  W/System.err:     at android.view.View.layout(View.java:19778)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
2018-12-27 10:50:03.414  W/System.err:     at android.view.View.layout(View.java:19781)
2018-12-27 10:50:03.414  W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6144)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
2018-12-27 10:50:03.414  W/System.err:     at android.view.View.layout(View.java:19781)
2018-12-27 10:50:03.414  W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6144)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
2018-12-27 10:50:03.414  W/System.err:     at android.view.View.layout(View.java:19781)
2018-12-27 10:50:03.414  W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6144)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
2018-12-27 10:50:03.414  W/System.err:     at android.view.View.layout(View.java:19781)
2018-12-27 10:50:03.414  W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6144)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
2018-12-27 10:50:03.414  W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)

**Comment by fufu100** [comment]
解决了吗
