### ISSUE TITLE
一加pro7 扫码报错 机型不适配

### ISSUE THREAD

**Issue by Dragonles** [bingoogolapple/BGAQRCode-Android#464]
08-30 13:53:13.179 32708-32721/cn.com.healthsource.dwfx D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@b6698c9[CaptureActivity]
08-30 13:53:13.185 32708-32708/cn.com.healthsource.dwfx W/System.err: java.lang.RuntimeException: autoFocus failed
        at android.hardware.Camera.native_autoFocus(Native Method)
        at android.hardware.Camera.autoFocus(Camera.java:1654)
        at cn.bingoogolapple.qrcode.core.CameraPreview.handleFocusMetering(CameraPreview.java:248)
        at cn.bingoogolapple.qrcode.core.CameraPreview.onScanBoxRectChanged(CameraPreview.java:148)
        at cn.bingoogolapple.qrcode.core.QRCodeView.onScanBoxRectChanged(QRCodeView.java:423)
        at cn.bingoogolapple.qrcode.core.ScanBoxView.calFramingRect(ScanBoxView.java:547)
        at cn.bingoogolapple.qrcode.core.ScanBoxView.onSizeChanged(ScanBoxView.java:533)
        at android.view.View.sizeChange(View.java:21041)
        at android.view.View.setFrame(View.java:21002)
        at android.view.View.layout(View.java:20862)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
08-30 13:53:13.186 32708-32708/cn.com.healthsource.dwfx W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:754)
        at android.view.View.layout(View.java:20865)
        at android.view.ViewGroup.layout(ViewGroup.java:6215)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3179)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2678)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1810)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8084)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1312)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1123)
        at android.view.Choreographer.doFrame(Choreographer.java:941)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1298)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7029)

08-30 13:53:14.057 32708-1062/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.105 32708-1063/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.148 32708-1064/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.219 32708-1065/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.265 32708-1062/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.295 32708-1063/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.332 32708-1064/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.376 32708-1065/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.399 32708-1062/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException
08-30 13:53:14.431 32708-1063/cn.com.healthsource.dwfx W/System.err: com.google.zxing.NotFoundException

**Comment by zk184174875** [comment]
猜测是一加7pro的分辨率没有适配

**Comment by zk184174875** [comment]
设置仅识别框内的时候，作者的计算框位置方法不适配，实际识别区域在框偏右上角，去掉仅识别框内选项
