### ISSUE TITLE
getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by Wkongge** [bingoogolapple/BGAQRCode-Android#473]
java.lang.RuntimeException: getParameters failed (empty parameters)
	at android.hardware.Camera.native_getParameters(Native Method)
	at android.hardware.Camera.getParameters(Camera.java:2265)
	at cn.bingoogolapple.qrcode.core.c.a(CameraPreview.java:193)
	at cn.bingoogolapple.qrcode.core.c.onTouchEvent(CameraPreview.java:182)

**Comment by bingoogolapple** [comment]
对应扫码库版本是多少？最新版还有这个问题吗

**Comment by fanjianli** [comment]
1.7.3还有这个问题 camera加锁 或者捕获这个异常都可以 好像作者不维护这个库了吧
