### ISSUE TITLE
Camera: app passed NULL surface

### ISSUE THREAD

**Issue by fiytodie** [bingoogolapple/BGAQRCode-Android#529]
`2020-08-31 16:03:20.402 22439-22439/xxx.xxx.xxx.xxx E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2020-08-31 16:03:20.402 22439-22439/xxx.xxx.xxx.xxx D/Camera: mHypnusCtrl is true
2020-08-31 16:03:20.403 22439-22439/xxx.xxx.xxx.xxx E/CheckPermission: camera-code= 3
2020-08-31 16:03:20.409 1362-3986/? I/CameraService: CameraService::connect call (PID 22439 "xxx.xxx.xxx.xxx", camera ID 0) for HAL version default and Camera API version 1
2020-08-31 16:03:20.670 1362-3986/? D/CameraService: CameraService::connect, oppo.camera.packname = xxx.xxx.xxx.xxx
2020-08-31 16:03:20.707 22439-22439/xxx.xxx.xxx.xxx D/Camera: app passed NULL surface
2020-08-31 16:03:20.711 22439-22439/xxx.xxx.xxx.xxx E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2020-08-31 16:03:20.734 22439-22439/xxx.xxx.xxx.xxx E/Camera: Error 2
`
使用的是zbar，截止到现在的最新版

从主界面进入扫描界面返回再进入反复几次后 ，会出现这个报错(代码回调的报错没有任何回调，只有这点日志报错)，摄像头预览画面卡死(有预览画面，一般是点进去1~5s才预览卡死，也有很多情况是扫描过程中才出现预览画面卡死)，可以手动调用stopcamera和startcamera恢复，但是没有代码里没有可以监听异常的地方就特别难受

开始以为是相机对象回收的问题，但是我这边也是
oncreate里zbarview.setDelegate(this);
onstart里 zbarview.startSpotAndShowRect();
onStop里zbarview.stopCamera(); 
onDestroy里zbarview.onDestroy();

试过把onstart和onStop里的换到 onResume和onPause，也看过网上的什么延时0.1~0.5s打开相机(startCamera)，但是都无效...

出现有一定的随机性，手上几台测试机，小米8出现的频率比较低，试个几十次才会出现一次，oppo(K1)的就异常高，大概4~5次就会出现

另外还会出现黑屏情况，但是这个是可以捕捉到的，设置个延时stop再start问题其实也不大
看起来像是回收的问题，最后都会出现Camera: Error 2

2020-08-31 16:42:48.926 26529-26529/xxx.xxx.xxx.xxx W/System.err: java.lang.RuntimeException: getParameters failed (empty parameters)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.hardware.Camera.native_getParameters(Native Method)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.hardware.Camera.getParameters(Camera.java:2316)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.handleAmbientBrightness(QRCodeView.java:343)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.onPreviewFrame(QRCodeView.java:310)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1344)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.os.Looper.loop(Looper.java:232)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7240)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
2020-08-31 16:42:48.929 26529-26529/xxx.xxx.xxx.xxx E/Camera: Error 2
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: java.lang.RuntimeException: getParameters failed (empty parameters)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at android.hardware.Camera.native_getParameters(Native Method)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at android.hardware.Camera.getParameters(Camera.java:2316)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.ProcessDataTask.processData(ProcessDataTask.java:64)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.ProcessDataTask.doInBackground(ProcessDataTask.java:118)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.ProcessDataTask.doInBackground(ProcessDataTask.java:10)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-08-31 16:42:49.030 26529-26529/xxx.xxx.xxx.xxx W/System.err: java.lang.RuntimeException: cancelAutoFocus failed
2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.hardware.Camera.native_cancelAutoFocus(Native Method)
2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.hardware.Camera.cancelAutoFocus(Camera.java:1546)
2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.CameraPreview.stopCameraPreview(CameraPreview.java:99)
2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView.stopCamera(QRCodeView.java:194)
2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at cn.bingoogolapple.qrcode.core.QRCodeView$3.run(QRCodeView.java:317)
2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.os.Looper.loop(Looper.java:232)
2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7240)
2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by fiytodie** [comment]
> 2020-08-31 16:03:20.402 22439-22439/xxx.xxx.xxx.xxx E/libc: Access denied finding property "vendor.camera.aux.packagelist" 2020-08-31 16:03:20.402 22439-22439/xxx.xxx.xxx.xxx D/Camera: mHypnusCtrl is true 2020-08-31 16:03:20.403 22439-22439/xxx.xxx.xxx.xxx E/CheckPermission: camera-code= 3 2020-08-31 16:03:20.409 1362-3986/? I/CameraService: CameraService::connect call (PID 22439 "xxx.xxx.xxx.xxx", camera ID 0) for HAL version default and Camera API version 1 2020-08-31 16:03:20.670 1362-3986/? D/CameraService: CameraService::connect, oppo.camera.packname = xxx.xxx.xxx.xxx 2020-08-31 16:03:20.707 22439-22439/xxx.xxx.xxx.xxx D/Camera: app passed NULL surface 2020-08-31 16:03:20.711 22439-22439/xxx.xxx.xxx.xxx E/libc: Access denied finding property "vendor.camera.aux.packagelist" 2020-08-31 16:03:20.734 22439-22439/xxx.xxx.xxx.xxx E/Camera: Error 2
> 使用的是zbar，截止到现在的最新版
> 
> 从主界面进入扫描界面返回再进入反复几次后 ，会出现这个报错(代码回调的报错没有任何回调，只有这点日志报错)，摄像头预览画面卡死(有预览画面，一般是点进去1~5s才预览卡死，也有很多情况是扫描过程中才出现预览画面卡死)，可以手动调用stopcamera和startcamera恢复，但是没有代码里没有可以监听异常的地方就特别难受
> 
> 开始以为是相机对象回收的问题，但是我这边也是
> oncreate里zbarview.setDelegate(this);
> onstart里 zbarview.startSpotAndShowRect();
> onStop里zbarview.stopCamera();
> onDestroy里zbarview.onDestroy();
> 
> 试过把onstart和onStop里的换到 onResume和onPause，也看过网上的什么延时0.1~0.5s打开相机(startCamera)，但是都无效...
> 
> 出现有一定的随机性，手上几台测试机，小米8出现的频率比较低，试个几十次才会出现一次，oppo(K1)的就异常高，大概4~5次就会出现
> 
> 另外还会出现黑屏情况，但是这个是可以捕捉到的，设置个延时stop再start问题其实也不大
> 看起来像是回收的问题，最后都会出现Camera: Error 2
> 
> 2020-08-31 16:42:48.926 26529-26529/xxx.xxx.xxx.xxx W/System.err: java.lang.RuntimeException: getParameters failed (empty parameters)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.hardware.Camera.native_getParameters(Native Method)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.hardware.Camera.getParameters(Camera.java:2316)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.QRCodeView.handleAmbientBrightness(QRCodeView.java:343)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.QRCodeView.onPreviewFrame(QRCodeView.java:310)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1344)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.os.Handler.dispatchMessage(Handler.java:106)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.os.Looper.loop(Looper.java:232)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7240)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at java.lang.reflect.Method.invoke(Native Method)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
> 2020-08-31 16:42:48.927 26529-26529/xxx.xxx.xxx.xxx W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
> 2020-08-31 16:42:48.929 26529-26529/xxx.xxx.xxx.xxx E/Camera: Error 2
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: java.lang.RuntimeException: getParameters failed (empty parameters)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at android.hardware.Camera.native_getParameters(Native Method)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at android.hardware.Camera.getParameters(Camera.java:2316)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.ProcessDataTask.processData(ProcessDataTask.java:64)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.ProcessDataTask.doInBackground(ProcessDataTask.java:118)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.ProcessDataTask.doInBackground(ProcessDataTask.java:10)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at android.os.AsyncTask$2.call(AsyncTask.java:333)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 2020-08-31 16:42:48.930 26529-26707/xxx.xxx.xxx.xxx W/System.err: at java.lang.Thread.run(Thread.java:764)
> 2020-08-31 16:42:49.030 26529-26529/xxx.xxx.xxx.xxx W/System.err: java.lang.RuntimeException: cancelAutoFocus failed
> 2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.hardware.Camera.native_cancelAutoFocus(Native Method)
> 2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.hardware.Camera.cancelAutoFocus(Camera.java:1546)
> 2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.CameraPreview.stopCameraPreview(CameraPreview.java:99)
> 2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.QRCodeView.stopCamera(QRCodeView.java:194)
> 2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err: at cn.bingoogolapple.qrcode.core.QRCodeView$3.run(QRCodeView.java:317)
> 2020-08-31 16:42:49.031 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.os.Handler.handleCallback(Handler.java:873)
> 2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.os.Handler.dispatchMessage(Handler.java:99)
> 2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.os.Looper.loop(Looper.java:232)
> 2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err: at android.app.ActivityThread.main(ActivityThread.java:7240)
> 2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err: at java.lang.reflect.Method.invoke(Native Method)
> 2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
> 2020-08-31 16:42:49.032 26529-26529/xxx.xxx.xxx.xxx W/System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by JackyKeke** [comment]
兄弟 看看 https://www.jianshu.com/p/586af3a2dc8d

**Comment by wscjy** [comment]
您好，我已收到您的邮件，我会尽快给您回复。
